### ISSUE TITLE
Cencab anomalies?

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#10]
Below is a file of cencab violations of our current jogging standards.  These all do look like real anomalies, and for inclusion in `anomaly.suppression`, with one possible exception:  In `hall.hoon`, there seems to be an alternative "flatwards" strategy, not allowed under our current standard.

@ohAitch: Let me know what you think.

[cencab.lint.txt](https://github.com/jeffreykegler/yahc/files/2866215/cencab.lint.txt)

**Comment by ohAitch** [comment]
Yep, real anomalies. The flatwards sections aren't even super aligned!

**Comment by jeffreykegler** [comment]
With the above referenced commit, this issue to ready to be closed.  Unless I hear otherwise, I will close it shortly.

@ohAitch  I've created some custom labels for this projects.  Black&white "Issue for Jeffrey" means the "ball is in my court" on an issue, which is the normal state of things.  Yellow "Ready to be closed" is for issues like this.  There's also a green "Question from Jeffrey" label, meaning I have some sort of question related to the issue.

**Comment by jeffreykegler** [comment]
Closed for the reason given in the previous comment.
