### ISSUE TITLE
TISCOL anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#12]
TISCOL (=:) is the only jogging-1 (jogging plus tail) hoon.  This comment will contain the file with the anomalies.  I will first follow up by documenting the jogging-1 format, before kicking this issue over to you as a question.  Here is the file with the anomalies.

[tiscol.lint.txt](https://github.com/jeffreykegler/yahc/files/2882071/tiscol.lint.txt)

The dill problem is, I think, an obvious extra space and therefore an anomaly.  For the zuse problems you may want to look at my (as yet unwritten) description of the jogging-1 indentation first, but the jogging is indented the same as the tail (both flush with the rune), and this does not follow the pattern of the other TISCOL's.

**Comment by jeffreykegler** [comment]
I have updated the [jogging document](https://github.com/jeffreykegler/yahc/blob/master/misc/jogging.mdl) for jogging-1 hoons.

@ohAitch -- I'm passing this over to you, with the question.  May I add all the lint warnings in tiscol.lint.txt above to `anomaly.suppressions`, and with that close this issue?

**Comment by ohAitch** [comment]
Yep! I think "jogging-1 runes only come in queenside, whether joined or split" is reasonable: trying to do kingside alignment gets you the "break-action" pattern from zuse, which is just weird.

(additionally, since the semantic of `=:` is "multiple `=.`", having their indentation be consistent is desirable and happens in the queenside case)

**Comment by ohAitch** [comment]
Oh hm, actually something I think most uses of `=:` get wrong: the `==` should be indented one stop more than the rune, not flush with it(as the jogging entire is not the last child)

**Comment by jeffreykegler** [comment]
Replaced by issue #17
