### ISSUE TITLE
Split vs joined 0-running hoons?

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#13]
@ohAitch -- a question:

I call a hoon 0-running if it consists only of a running -- no head no tail.  The 0-running hoons are BUCCEN, BUCCOL, BUCWUT, COLSIG, COLTAR, WUTBAR, WUTPAM.

These take two forms in the `arvo/` corpus, "split" and "joined", according to whether they .  "Split" is less common but not rare -- 133 of the 1232 occurrences are "split".  (This is frm count made using `grep`, but I expect it's pretty accurate).

From `hoon.hoon`@3153, here is an example of "joined".

```
      :~  [ral ruz]
          [8 128]
          [(mod (sub 960 (mod (add 8 ral) 512)) 512) 0]
          [64 (~(net fe 6) ral)]
      ==
```

and here from `scad` in `hoon.hoon` @11683 is the start of a very long example of "split":

```
    :~
      :-  '_'
        ;~(pfix cab (stag %bccb wide))
      :-  ','
        ;~(pfix com (stag %bcsm wide))
      :-  '$'
        ;~  pose
          ;~  pfix  buc
            ;~  pose
              (stag %leaf (stag %tas (cold %$ buc)))
              (stag %leaf (stag %f (cold & pam)))
              (stag %leaf (stag %f (cold | bar)))
              (stag %leaf (stag %t qut))
              (stag %leaf (sear |=(a/coin ?:(?=($$ -.a) (some +.a) ~)) nuck:so))
            ==
          ==
          (stag %bcsm rump)
        ==
      :-  '%'
 ```
Split is less common, but the existing examples are very long, so that if a split 0-jogging is not acceptable, many misindentation warnings will result.

The question: should `hoonlint` accept "split" 0-joggings?  Or only "joined" ones?

**Comment by jeffreykegler** [comment]
I note in Curtis' last Mars interview of around a year ago, he says that he thinks it would be impossible to write a `hoonfmt`.  I think we are well along on proving this wrong, something I suspect Curtis would have been glad to see.

**Comment by jeffreykegler** [comment]
I notice also that, if one wants to take that POV, the "split" vs. "joined" could be seen as a "chess-sidedness" bias instead, so that we have "split" == "kingside" and "joined" == "queenside".

**Comment by ohAitch** [comment]
…I may have spoken too quickly about "break-action" style in #12

I think disallowing split =: is still the right call, but it's definitely seeing active use in running yeah. Perhaps a soft cap would be best here: a hoon running shorter than ~10 lines should not be split, while one longer than ~100 should not be joined(pick whatever numbers are a good safety margin away from what is substantiated by the code)

This project is definitely in part me going "surely it can't be that hard! it'll just require finding and getting into a lot of specific details"; agree that we're well on the way there.

Wrt scad in particular: honestly the correct stylistic solution here is to refactor `++stew` to accept an even-length list of alternating characters and parsing rules, and post-process that into a list of pairs(or I think actually a map) inside the function itself. This would let you get rid of the irregularly-indented `:-`s and save an indent stop by making the whole expression a 0-jogging queenside `:~` - not exactly conventional, but a lot cleaner certainly.

**Comment by jeffreykegler** [comment]
I implemented split and joined 0-running hoons.  I now need to create a stub in the code for minimum line count for split 0-running hoons; and for maximum line count for joined 0-running hoons.  This will allow command-line options and inline directives to control the usage of split vs. joined.  Once that is done, I will mark this issue ready for closing.

**Comment by jeffreykegler** [comment]
Based on the above, I believe this issue is ready to be closed.

**Comment by jeffreykegler** [comment]
Closed as per the above.
