### ISSUE TITLE
TISCOL anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#17]
@ohAitch -- [tiscol.lint.txt](https://github.com/jeffreykegler/yahc/files/2913315/tiscol.lint.txt)
I have updated the [whitespace doc](https://github.com/jeffreykegler/yahc/blob/master/misc/whitespace.md) for jogging-1 hoons, the remaining anomalies for which are in the file above.  I believe these can all be added to `anomaly.suppressions`.  Let me know.

[ This replaces issue #12 , which I am closing. ]

**Comment by jeffreykegler** [comment]
I may be able to classify these by issue, instead of by hoon.  In any case, there is no value-added in this ticket, so no loss in closing it.  Marking "ready to be closed".

**Comment by ohAitch** [comment]
Can confirm, everything in there looks like anomalies as described in #12;
but if there were issues cross-rune classification would be reasonable.

(There might be value in an immediately-closed "anomaly type"-labeled issue
for what I described as the "break-action pattern in zuse", for
organizational purposes, but probably the "lint justification" list should
be in e.g. linter source comments and not floating around the gh issue
tracker)

**Comment by jeffreykegler** [comment]
I added 4 of these to `anomaly.suppressions`.  The rest actually fall into a pattern ("split tiscol"
) so that I will open a new issue with them, to see if we want hoonlint to be OK with them.  Details will follow in that new issue.

Marking this issue "ready to be closed".

**Comment by ohAitch** [comment]
An issue for https://github.com/jeffreykegler/yahc/issues/13#issuecomment-466732963 makes sense yup

**Comment by jeffreykegler** [comment]
Closed as per the above.
