### ISSUE TITLE
SEMSIG anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#18]
[semsig.lint.txt](https://github.com/jeffreykegler/yahc/files/2921008/semsig.lint.txt)
Here are the current SEMSIG anomalies.  All but the ones in zuse my guess is that they should be added to `anomaly.suppressions`.

The zuse ones are warnings for cases where more than one runstep is on a line.  I have already coded an exception for when the first line contains more than one runstep, but here we have other cases.  One of them could be interpreted as paired runsteps, which you wanted accepted, but for SEMCOL this was one of the cans kicked down the road in `later.suppressions`.

Possible choices:

1.) Allow the initial lines of a running to have multiple runsteps, with the first singleton line ending the exception.

2.) Allow multiple runsteps on running lines is *all* of its running lines have more than one runstep -- in other words, if there are no singletons.

Note that 2.) is a special case of 1.)  Also note that making either 1.) or 2.) the rules would allow pairs, except that, unlike for the pair in a jog, there would be no enforcement of alignment.

@ohAitch -- Let me know what you think.

**Comment by ohAitch** [comment]
Yup, zuse was covered in #30, most of these are plain odd-indent anomalies

I will note  hoons/arvo/sys/hoon.hoon 5329,5347  are doing the equivalent
of the "one-line lute" thing, so I wouldn't say there's actually a  missing
newline - though I agree that if the running was /multiline/ the == would
definitely want to be separate, perhaps somethng about "vertical or
horizontal alignment"

**Comment by jeffreykegler** [comment]
I added most of those to `anomaly suppressions` in commit 151d988, and will move the others into new issues.  Issue #32 is one I've done already.  I am marking this as "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
