### ISSUE TITLE
WUTBAR, WUTPAM anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#19]
[wutbarpam.lint.txt](https://github.com/jeffreykegler/yahc/files/2921614/wutbarpam.lint.txt)
I implemented both split and joined 0-running hoons, and will introduce a stub that will allow for a minimum length of split and a maximum length of joined 0-running hoons.  I'll follow up with that back in issue #13 .

Here I think this are all candidates for `anomaly.suppressions`, with the possible exception of jael, where you might say a pseudo-joined style is being used.  But it would be the only case for WUTBAR/WUTPAM in the whole `arvo/` corpus, suggesting it's a error and not a pattern.

@ohAitch -- let me know what you think.

**Comment by ohAitch** [comment]
Yup, the outdented blank comments should certainly be outdented all the way
to the running rune, and the zuse newline is good.

As for pseudo-joined style, it looks like some of clay is doing something
similar? But yeah just outdenting them seems fine.

**Comment by jeffreykegler** [comment]
Added suppressions to `anomaly.suppressions`in commit 0666382.  Marking as "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
