### ISSUE TITLE
A few TISTIS anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#20]
[tistis.lint.txt](https://github.com/jeffreykegler/yahc/files/2922452/tistis.lint.txt)
A few TISTIS anomalies.  The one in `eyre` is an attempt at a criss-cross TISTIS line, but the WUTLUS's are just too close together for that to work.

@ohAitch -- I think these all should go into `anomaly.suppressions`.  Let me know what you think.

**Comment by ohAitch** [comment]
The underindented ones are in fact underindented; and uncrossing the triple wutlus seems reasonable yup

**Comment by jeffreykegler** [comment]
Added to `anomaly.suppressions`.  I am now marking this "Ready to be closed"

**Comment by jeffreykegler** [comment]
Closed as per the above.

**Comment by ohAitch** [comment]
I guess the first lint here is a good second example of the reanchoring
pattern you mentioned, this one also feels "off" and like it would be
better served by indenting everything to not be reanchored? (Presumably the
== is no longer flagged as erroneous, but in this case all of the jog heads
are vertically aligned with the parent rune which seems bad)

Tempted to say reanchoring is only valid when the reanchored body is the
last child of the anchor brick rune, thus getting rid of the
reanchor-offset machinery - what sorts of problems would that cause?
