### ISSUE TITLE
"Staircase" comments

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#21]
@ohAitch -- I am currently working on batteries, which are complicated, but (thankfully) relatively anomaly-free.  In the inter-cell comments, there are a lot of "staircase" comments, which by my current version of the comment alignment rules are anomalies.  Should I change the rules to allow these?

Here is an example of what I am calling "staircase" comments:

```
=== hoons/arvo/lib/hood/helm.hoon ===
 10  |%                                                      ::  ::
 11> ++  part  {$helm $0 pith}                               ::  helm state
 12  ++  pith                                                ::  helm content
 13    $:  bur/(unit (pair ship mace:ames))                  ::  requesting ticket
 14        hoc/(map bone session)                            ::  consoles
 15    ==                                                    ::
 16  ++  session                                             ::
 17    $:  say/sole-share                                    ::  console state
 18        mud/(unit (sole-dialog @ud))                      ::  console dialog
 19>   ==                                                    ::
 20  ::                                                      ::  ::
 21  ::::                                                    ::  ::
[ hoons/arvo/lib/hood/helm.hoon 19:5 Test::Whitespace whap5d cell #3 @22:3; comment overindented by 2 ]
 22!   ::                                                    ::  ::
 23  ++  hood-begin                                          ::  begin command
 24    $:  his/@p                                            ::  identity
 25        tic/@p                                            ::  ticket
 26        eny/@t                                            ::  entropy
```

**Comment by ohAitch** [comment]
hah, the sideways-tilde separator is somewhat old-fashioned but pretty prominent yeah. How hard would it be to special-case specifically staircases? (Possibly something liberal like, "two comment lines can be followed by an indented comment line", though I admit having hoonlint fix up misindented-by-one staircases would be amusing)

**Comment by jeffreykegler** [comment]
@ohAitch staircase comments come up so often I've already thought out the implementation strategy.

I now have a practice for implementation of starting out fascist and then liberalizing based on the spurious warning.  Staircase comments seem to follow a very strict pattern.  We'll find out in any case.

I am now marking this as a "Jeffrey" task.

**Comment by jeffreykegler** [comment]
This is complete and tested, and I have documented the details of my interpretation of "staircase comments": https://github.com/jeffreykegler/yahc/blob/master/misc/whitespace.md .  I did staircase comments first because staircase comments occur all over, and they clutter the other tickets.

I will now mark this "ready to be closed" and, unless I hear otherwise, close it shortly.

**Comment by jeffreykegler** [comment]
Closed as per the above.
