### ISSUE TITLE
Missing comments between battery cells

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#22]
@ohAitch -- Here's about a dozen missing comments between battery cells.  I think these are all anomalies.  Agree?

[whap5d.lint.txt](https://github.com/jeffreykegler/yahc/files/2943253/whap5d.lint.txt)

**Comment by ohAitch** [comment]
There appear to be considerably more >s than corresponding !s in the lint
output; but I can certainly confirm that blank lines should not be allowed
anywhere in hoon! (Okay strictly speaking .udon embeds will
near-inescapably have it, but udon is an abomination wrought by two people
both of whom are no longer at the company - tbf me and Curtis)

The doubly-commented block it's also complaining about is interesting, the
outer outdented comment layer should just not be there; but lint-wise just
complaining about it violating indentation seems correct.

**Comment by jeffreykegler** [comment]
Added suppressions in last 2 commits, but suppressions apparently already taken care of in other work.  Marking as "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
