### ISSUE TITLE
WUTHEP kingside anomalies

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#3]
@ohAitch These are kingside WUTHEPs, with whose jogging is aligned queenside.  All but one of these has queenside jogs.  As before, if these are simply mistakes, I want to add them to the suppressions and close the issue.  If these fit a pattern, or are grey-area, let me know.
[C.kwuthep.txt](https://github.com/jeffreykegler/yahc/files/2800516/C.kwuthep.txt)

**Comment by ohAitch** [comment]
Hm, by "kingside"/"queenside" are you referring here to the indentation of
the first element? These (and #2) all look like mistakes on the line with
the >

If this is the common type of error, I think I would like to define the
detection for "kingside" as "most clauses are indented by 1", and
"queenside/mixed queenside" as "most clauses are indented by 2". The
corrective action required by "proper kingside" is then "all clauses are
indented by 1, first-child is indented by 2, clause bodies are indented
past clause heads"; correspondingly "proper queenside/mixside" is "all
clauses indented by 2, first-child indented by 3, clause bodies either
backdented to 1 or indented beyond 3(usually, after two spaces on the same
line as their corresponding head)"

I think YAHC accounts for this, but note that same-line kingside(whether or
not it's surrounded by queenside) breaks "an indent is usually an even
number of spaces" where the clause-head(e.g. %atom) itself has an odd
length.

**Comment by jeffreykegler** [comment]
The "chesssidedness" in both these tickets is mixed, and I rather arbitrarily divided them into king/queen based on the indentedness of the 1st child.

I deal with the potential "oddness" of "same-line kingside", but allowing *any* indentedness -- I do not currently check for alignment between jogs.  So I am safe from "false alarms" on odd indents, but currently that's at the expense of ignoring other problems.

**Comment by ohAitch** [comment]
I don't think I would describe e.g. "hoons/arvo/lib/hood/helm.hoon 231:3"
as mixed? That one clearly just has an overindented -.saw, some of the
longer ones don't have full context obvs.

I would define individual item sidedness as "is the head less indented than
the body, or more"("equally" is an error that I don't think appears); the
items as a whole / 1st child flow from that. Specifically,
- only the == should be all the way outdented
- all the item heads should be aligned
- the 1st child should be indented one more than those, and
- all things equal less indentation is better("true kingside" as seen in
the docs, when all the items themselves are kingside; in general mixed form
should not be too common)

**Comment by jeffreykegler** [comment]
I'll go back and produce more perspicuous error messages based on the above, and probably take care of checking for one-line kingside job alignment at the same time.  Once done, I'll deal with these two issues, perhaps by closing them in favor of one or more new issues.

**Comment by jeffreykegler** [comment]
Replaced by issue #4
