### ISSUE TITLE
Multi-runstep lines

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#30]
@ohAitch: we already allow the 1st line of a running to have multiple runsteps.  I suggest we extend that to allow any number of initial lines of a running to be multi-runstep.  In cases like this:

```
=== hoons/arvo/sys/vane/eyre.hoon ===
1476        ==
1477      ::
1478      ++  set-cookie
1479        |=  {key/@t val/@t}
1480>       %+  rap  3  :~
[ hoons/arvo/sys/vane/eyre.hoon 1481:14 Test::Whitespace tallColsig split 0-running runstep #2 @1481:12; missing newline @1481:12 ]
[ hoons/arvo/sys/vane/eyre.hoon 1481:14 Test::Whitespace tallColsig split 0-running runstep #2 @1481:14; overindented by 5 ]
[ hoons/arvo/sys/vane/eyre.hoon 1481:19 Test::Whitespace tallColsig split 0-running runstep #3 @1481:17; missing newline @1481:17 ]
[ hoons/arvo/sys/vane/eyre.hoon 1481:19 Test::Whitespace tallColsig split 0-running runstep #3 @1481:19; overindented by 10 ]
1481!         key  '='  val
1482>         ::  '; HttpOnly'  ?.(sec '' '; Secure')  ::  XX security
1483          cookie-domain
1484          '; Path=/; HttpOnly'
1485        ==
1486      ++  need-ixor  (oryx-to-ixor (need grab-oryx))
```

it seems that the code is quite reasonably laid out, and we should allow it.  We'd require that runsteps be separated by exactly one stop.

An equivalent way of stating the rule is that multi-runstep lines are allowed in a running, but that any single-runstep line can only be followed by another single-runstep line.

@ohAitch -- agree?

**Comment by ohAitch** [comment]
Seems like a good balance of "mostly runnings should be one per line" and
"an unstructured list is sometimes just an informally structured list
indented accordingly", yup!

(Honestly this might be a good example use for "::nolint" one stop after
the :~ on the first line, perhaps even with a hoonfmt that puts it in in
the no-single-runstep case - a bit cheeky though)

**Comment by jeffreykegler** [comment]
This cleared up over 800 spurious warnings.  `arvo.lint.out` count is now down to 2474.  Marking 'ready to be closed'.

**Comment by jeffreykegler** [comment]
Closed as per the above.
