### ISSUE TITLE
Split TISCOL

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#31]
Here is a new pattern, "split TISCOL".  It's not really orthogonal with the general backdenting patter, but what occurrences there are, are quite regular.  There are 6 of them, all in `zuse.hoon`.

Here's an example:

```
        =:
          key  (~(net fe 7) key)
          blk  (~(net fe 7) blk)
        ==
        %-  ~(net fe 7)
        (be & (ex key) blk)
```

And here's the full output: 
[tiscol-split.lint.txt](https://github.com/jeffreykegler/yahc/files/3110121/tiscol-split.lint.txt)

@ohAitch -- What is the verdict?  The same mistake, repeated 6 times?  Or a legal pattern, to be allowed by `hoonlint`?

**Comment by ohAitch** [comment]
The `==` outdent is just too misleading, not legal ^-^

**Comment by jeffreykegler** [comment]
You already addressed this in https://github.com/jeffreykegler/yahc/issues/13#issuecomment-466732963 , I notice.  OK, question answered.  I am marking this issue "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.

**Comment by jeffreykegler** [comment]
Note for the record: This originated from issue #17.
