### ISSUE TITLE
TISSIG TISTIS's

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#33]
This issue replaces issue #27 which I will close.
I add new facilities to the warnings, and using them, reworded these.  Hopefully they are clearer.  Warnings can now have "details", making them multi-line.  (In the warnings in this lint output, the additional line is clutter, just a trace message.)

@ohAitch -- I think all of these should be added to `anomaly.suppressions`.  Do you agree?

[tissig.lint.txt](https://github.com/jeffreykegler/yahc/files/3123177/tissig.lint.txt)

**Comment by ohAitch** [comment]
I vaguely remember this being resolved in a different discussion as "the `==` should be aligned vertically with the `=~`, which unlike most runes is allowed to have things outdented from it". Does that sound right?

**Comment by jeffreykegler** [comment]
I have switched over from Github-issue-driven development to documentation-driven development.  This issue will be dealt when it comes up in the documentation-driven development.  Accordingly, I am marking this issue "Ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
