### ISSUE TITLE
"In the middle" runstep comments

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#34]
This is the first of my more verbose lint outputs.  Hopefully future issues will tend to be more targeted by specific anomaly as well.

These are all "off by one stop" runstop comment indents halfway between the correct indents, which are either at the anchor column or aligned with the runstep.

@ohAitch -- I believe all of these should be added to `anomaly.suppressions`.  Let me know what you think.

[by2.lint.txt](https://github.com/jeffreykegler/yahc/files/3132908/by2.lint.txt)

**Comment by ohAitch** [comment]
861:9 862:9 863:9 "is underindented by 2, inter-comment indent should be 9, anchor column is 827:9 `;~`" - it looks like :9 is a correct indent and not anomalous?

447:3 is a failed staircase comment detection

generally, it looks like runes with inter-indent style are at least consistent about using that style, but normalizing to "aligned with anchor column" seems good yup

**Comment by jeffreykegler** [comment]
Thanks for catching 447:3, which I'd meant to remove.

And also a good catch, for 861:9, 862:9, 863:9, which I had not noticed.  Something may be wrong in my logic with them.

I will add the others to `anomaly.suppressions`.

**Comment by jeffreykegler** [comment]
The trouble with the explanatory details, is that they make my mistakes all too obvious. :-)

**Comment by jeffreykegler** [comment]
I broke two issues out from this, and dealt with the rest in commit 0f27628 .  Marking as "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
