### ISSUE TITLE
Missed staircase comment

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#35]
Broken out from issue #34 .

This looks like a spurious warning on a perfectly good staircase comment.

```
 445  ::
 446  ::::
[ hoons/arvo/lib/down-jet/parse.hoon 448:1 Test::Whitespace tissig:comment-indent runstep #2 @447:3; comment overindented by 2
  0as1-running
  inter-comment indent should be 3
  pre-comment indent should be 3
  anchor column is @97:3 "=~"
]
 447!   ::
```

**Comment by jeffreykegler** [comment]
I believe this is indeed an anomaly -- the *entire* staircase is shifted left one stop.  This listing adds the rune line and the diagnostics for the upper riser and tread of the staircase, which makes it clearer:

```
  95    [[0 0] ~ (a q.tub) [0 0] ~]
  96  --  ==
  97>   =~
  98  |%
  99  ++  strip
------
 443    --
 444  --  
[ hoons/arvo/lib/down-jet/parse.hoon 97:3 Test::Whitespace tallTissig 0as1-running @445:1; comment underindented by 2 ]
 445! ::
[ hoons/arvo/lib/down-jet/parse.hoon 97:3 Test::Whitespace tallTissig 0as1-running @446:1; comment underindented by 2 ]
 446! ::::
[ hoons/arvo/lib/down-jet/parse.hoon 448:1 Test::Whitespace tissig:comment-indent runstep #2 @447:3; comment overindented by 2
  0as1-running
  inter-comment indent should be 3
  pre-comment indent should be 3
  anchor column is @97:3 "=~"
]
 447!   ::
 448> |%
 449  ++  nesting  $%  {$bloq *}                              ::  Used for fishing
 450                   {$item *}
```

**Comment by jeffreykegler** [comment]
@ohAitch -- per the previous comment, I think this anomaly should be added to `anomaly.suppressions`.  Let me know what you think.

**Comment by ohAitch** [comment]
Could you elaborate on "is shifted left by one stop"? My understanding of a staircase comment is broadly speaking a comment on column 1, a double comment on column 1, and then a comment on column 3 - is there a column -1 floating around?

**Comment by jeffreykegler** [comment]
The staircase itself is set up correctly, but it is should be aligned based on the anchor column.  The staircase is aligned, as you note, based on column 1.  The anchor column is column 3, as reported by the detail line:

```
  anchor column is @97:3 "=~"
```

And here is line 97, with a little context to make the alignment of the TISSIG stand out:

```
96  --  ==
97>   =~
98  |%
```

So a perfectly formed staircase, but aligned wrt column 1 instead of column 3, so as I phrased it, "shifted left by one stop".

@ohAitch -- sound right?

**Comment by ohAitch** [comment]
Ah, so the issue is generically the "inverse-indented =~" pattern - do the |%s have similar lints?

Are there any non-anomalous staircase comments in the codebase that _are_ on column 3 or 5 or w/e?

**Comment by jeffreykegler** [comment]
AFAICT there are no staircase comments not on column 1.

Note the basic logic is syntax-tree driven, so that hoonlint generally of
indentation as correct (or otherwise) relative to a parent node, and not in
absolute terms.  We could say staircase comments must be at column 1, but
that would, make the messages for the surrounding comments pretty
mysterious -- you'd have a "correct" (in the absolute sense) staircase
surrounded by comments reported as incorrect, and the child of a misaligned
rune.

I think it's probably clearest to report the staircase as a issue, and if
that is initially unintuitive, it could be thought of bringing out issues
not easily apparent to the unaided eye.

**Comment by ohAitch** [comment]
I think the solution there is to report an attempted staircase in a non-column-1 anchor context as an error, "if a staircase were allowed this is the indentation it would be at but staircase comments can only exist fully outdented".

Though in this particular case, the pattern that needs to be recognized is "`=~` with an outdented anchor column" - this seems slightly different from reanchoring, but is the primary indentation convention for `=~` twigs greater than ~20 lines.

**Comment by jeffreykegler** [comment]
I can certainly change the logic to not recognize a staircase except at column 1.  That's not hard.

As for recognizing "staircase attempts", those can look awfully like other comment mis-indentations.  Perhaps just leave it with treating them as non-staircase comments and reporting the indentation accordingly, as is done in this case?  Otherwise it is a lot of effort to modestly improve the reporting of an error than occurs in the corpus exactly once.

**Comment by ohAitch** [comment]
Especially since I maintain it is not an error, being aligned with the preceding `--` and following `|%` as it is; fair enough!

**Comment by jeffreykegler** [comment]
OK, so there is an inverse re-anchoring here.  Does this occur with other runes or is it just a TISSIG thing?

**Comment by ohAitch** [comment]
I think it is just a TISSIG thing, nothing else n-ary routinely has several `|%`s stuck into it :)

**Comment by jeffreykegler** [comment]
TISSIG does seem to be special in many ways.

**Comment by jeffreykegler** [comment]
OK, I went through the lint output for `hoons/arvo/lib/down-jet/parse.hoon` and found a warning for the parent TISSIG on line 97.  It is reported as overindented by 2 -- if it were indented correctly the staircase would also be correct.

```
   6  =,  html
   7  =,  format
   8> =+  =~
   9  |%
  10  ++  loca  |*(a/_* {p/@u q/a})  
------
  95    [[0 0] ~ (a q.tub) [0 0] ~]
  96  --  ==
[ hoons/arvo/lib/down-jet/parse.hoon 8:1 Test::Whitespace tallTislus backdented element #2 @97:3; overindented by 2 ]
  97!   =~
  98  |%
  99  ++  strip
```

**Comment by jeffreykegler** [comment]
I will add this to `anomaly.suppressions`.  Re-marking as "issue for jeffrey".

**Comment by jeffreykegler** [comment]
Added to `anomaly.suppressions` already for issue #28 .  Marking as "ready to close".

**Comment by jeffreykegler** [comment]
Closing as per the above.
