### ISSUE TITLE
Staircase comments at column 3 in zuse.hoon

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#38]
I implemented the restriction of staircase comment s to column 1, thinking that all staricases in the corpus began at column 1 and therefore this would cause no new warnings.

It turns out many staircases in `zuse.hoon` start at column 3.  Below is a lint output showing them.

@ohAitch -- I plan to revert the "fix", and to allow stairase comments to be aligned at any column, as was previously the case.  Do you agree?

[staircase3.lint.txt](https://github.com/jeffreykegler/yahc/files/3140407/staircase3.lint.txt)

**Comment by jeffreykegler** [comment]
This issue is an outgrowth of the discussion in issue #35.

**Comment by ohAitch** [comment]
Yup, looks like I was completely mistaken and they do in fact occur, they
sure look reasonable. The resolution to #35 (as "okay but the cores it's
separating are in fact on column 1") stands, but the general restriction
appears unsubstantiated.

**Comment by jeffreykegler** [comment]
Fixed in commit a1fadc4.  Marking "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
