### ISSUE TITLE
Horizontal backdent gaps, unaligned

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#41]
Currently I require all horizontal gaps (that is, gaps with no newlines) to be exactly one stop long.  This issue is about anomalies where alignment with adjacent lines does not seem to be an issue. I think therefore, these all belong in `anomaly.suppressions`.

@ohAitch -- do you agree?

There are 61 of these.  Here's the lint output:

[joined.lint.txt](https://github.com/jeffreykegler/yahc/files/3185678/joined.lint.txt)

**Comment by ohAitch** [comment]
It was at some point supposed to be ford style that / runes use two-stop gaps instead of one, but nobody's been doing that and they should just be regularized to one-stop yup

And everything else looks like just errors, agree

**Comment by jeffreykegler** [comment]
All warnings added to `anomaly.suppressions` in the above referenced commit.  Marking as "ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above
