### ISSUE TITLE
Horizontal backdent gaps, aligned

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#42]
This issue is about anomalous horizontal backdent gaps, where there seems to be some attempt at alignment with respect to nearby lines.

The strict approach is to insist all these gaps be exactly one stop.

More liberal approaches are possible, allowing at least some of these.  But they'd be hard to implement.  Also, our goal is `hoonfmt`, and it is just a fact that automated whitespacing is not as "artistic" as human whitespacing.  [ At least as seen by the human :-) ]  From this point of view all these ad hoc customizations are necessary costs of automated checking.  I know that in C and Perl, I just accept the whitespacing of the tools, and don't miss all the erratic artistry I applied before they were available.

If we follow the strict approach, all of these go into `anomaly.suppressions`.

@ohAitch -- let me know what you think.

There are 54 of these.  Here is the lint output:

[aligned.lint.txt](https://github.com/jeffreykegler/yahc/files/3185803/aligned.lint.txt)

**Comment by ohAitch** [comment]
If generalizing the aligned kingside logic to "second-children of consecutive chained three-child runes seem to be aligned, allow this" would be difficult don't bother with it yup - perhaps another good use for a "within this arm don't enforce indents" type marker

(the other major pattern I see are running `:-`s for synthetic kingside; that might be well-enough specified, otoh should probably be refactored using a `~[a b c d e f] -> ~[[a b] [c d] [e f]]` gate and "running allows jogging" indentation convention)

**Comment by jeffreykegler** [comment]
Implementing alignment for chained 3-fixed runes would be of the same level of difficulty as it was for joggings, so I'll take that on next.

In the corpus chaining is done for TISFAS (=/); TISTAR (=*); WUTDOT (?.); WUTCOL (?:); WUTPAM (?@); and WUTSIG (?~).

**Comment by jeffreykegler** [comment]
I have divided this issue up into issue #45 , issue #46 and issue #47 .  I am marking this issue "ready to be closed"

**Comment by jeffreykegler** [comment]
Closed as per the above.
