### ISSUE TITLE
FASWUT two-step indents

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#43]
While most ford runes use the standard one-stop indent, the two-stop indents did creep in,. 
 For FASWUT there are a lot of them: 196.  They all look pretty much the same:

```
/?    310
```

Choices include

1.) Make FASWUT a non-orthogonal special-case.

2.) Use `hoonlint` to clean up the ford two-stop indents, which means for the time being add them to `anomaly.suppressions`.

@ohAitch -- let me know what you want here.

Here is the lint output:

[faswut.lint.txt](https://github.com/jeffreykegler/yahc/files/3193529/faswut.lint.txt)

**Comment by ohAitch** [comment]
Either's fine by me, there's a pretty even mix of them being next to other two-stop gapped lines vs alone or next to one-stop gaps.

**Comment by jeffreykegler** [comment]
For the time being at least, then, `hoonlint` will complain about all Ford 2-stop indents.  I am marking this as "Ready to be closed".

**Comment by jeffreykegler** [comment]
Closing this, as per the above.
