### ISSUE TITLE
Chained rune inter-line alignment "miss"

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#48]
I've fixed Github issue #47, so that `hoonlint` now recognizes inter-line alignments, and all the issues of that issue disappear except this one.  As the diagnostics below indicate, the alignment of element #2 on line 909 is at column 13, but the inter-line alignment had previously (lines 891-893) been established as at column 16.  I think should be classified as a misindent and added to `anomaly.suppresssions`.  Agree?

Details follow:

```
  887    ~%  %muk  ..muk  ~
  888    =+  ~(. fe 5)
  889    |=  {syd/@ len/@ key/@}
  890    ?>  &((lte (met 5 syd) 1) (lte (met 0 len) 31))
  891>   =/  pad      (sub len (met 3 key))
  892>   =/  data     (weld (rip 3 key) (reap pad 0))
  893>   =/  nblocks  (div len 4)  ::  intentionally off-by-one
  894    =/  h1  syd
  895    =+  [c1=0xcc9e.2d51 c2=0x1b87.3593]
  896    =/  blocks  (rip 5 key)
  897    =/  i  nblocks
-------
  905      =.  hi  (rol 0 13 hi)
  906      =.  hi  (sum (sit (mul hi 5)) 0xe654.6b64)
  907      $(i (dec i))
  908    =/  tail  (slag (mul 4 nblocks) data)
[ hoons/arvo/sys/hoon.hoon 909:13 Test::Whitespace tisfas:hgap joined backdent element #2 of @909:3 is at @909:13; should be one of @909:11 (tight); @909:16 (inter-line)
  3-backdented
  inter-line alignment is 16, see 891:16 892:16 893:16
]
  909!   =/  k1    0
  910    =/  tlen  (dis len 3)
  911    =.  h1
  912      ?+  tlen  h1  ::  fallthrough switch
  913        $3  =.  k1  (mix k1 (lsh 0 16 (snag 2 tail)))
```

**Comment by ohAitch** [comment]
Hm do we have a category for "correct answer by linter but not the line that should be fixed"?

Like, the actual anomaly is 898:11, which should not have been reanchored in that fashion, and instead split on the next line; thus interrupting interline alignment and allowing 908-10:13 to cleanly reestablish itself. But that's clearly in "judgement call" territory, and locally hoonlint is completely right that 909 is doing a discordant thing.

**Comment by jeffreykegler** [comment]
I have switched over from Github-issue-driven development to documentation-driven development.  This issue will be dealt when it comes up in the documentation-driven development.  Accordingly, I am marking this issue "Ready to be closed".

**Comment by jeffreykegler** [comment]
Closed as per the above.
