### ISSUE TITLE
Centis anomalies?

### ISSUE THREAD

**Issue by jeffreykegler** [jeffreykegler/yahc#9]
I am finishing up the 1-jogging hoons and will then move on to the other jogging hoons.

@ohAtich -- Below is the lint file for CENTIS (%=) anomalies, according to our current jogging standards. I think these are all, indeed, anomalies and therefore for inclusions in `anomaly.suppression`.  Let me know your thoughts.

[centis.lint.txt](https://github.com/jeffreykegler/yahc/files/2866133/centis.lint.txt)

**Comment by ohAitch** [comment]
Yep those all look like correct corrections
hoon:2325 is interesting? But indenting everything in it(including the `==`) seems reasonable
ames:1323 is doing the "sidenote" or w/e we decided to call it stacked indentation style, but should be a `%_` instead

**Comment by jeffreykegler** [comment]
Ready for closure as of commit 72a8e6e just referenced.

**Comment by jeffreykegler** [comment]
Closed for the reason given in the previous comment.
